import test from 'node:test';
import assert from 'node:assert/strict';
import { rule as targetSdkRule, MIN_REQUIRED_TARGET_SDK } from '../src/rules/android/target-sdk.js';
import {
  packageNameRule,
  versionCodeRule,
  versionNameRule,
} from '../src/rules/android/manifest-basics.js';
import { rule as permissionsInventoryRule } from '../src/rules/android/permissions-inventory.js';
import { isAutoGeneratedPermission } from '../src/rules/android/permission-catalog.js';
import { runRules } from '../src/rules/index.js';
import {
  manifestDataPassing,
  manifestDataFailingTargetSdk,
  manifestDataMissingFields,
  manifestDataSensitivePermissions,
} from './fixtures/manifest-samples.js';

test('target-sdk rule fails below the required floor (catches the real Aug 2026 deadline)', () => {
  const result = targetSdkRule.evaluate(manifestDataFailingTargetSdk);
  assert.equal(result.status, 'fail');
  assert.match(result.detail, /35/);
  assert.match(result.detail, new RegExp(String(MIN_REQUIRED_TARGET_SDK)));
});

test('target-sdk rule passes at or above the required floor', () => {
  const result = targetSdkRule.evaluate(manifestDataPassing);
  assert.equal(result.status, 'pass');
});

test('target-sdk rule warns (not fails) when the value could not be read at all', () => {
  const result = targetSdkRule.evaluate(manifestDataMissingFields);
  assert.equal(result.status, 'warn');
});

test('manifest-basics rules pass on a well-formed manifest', () => {
  assert.equal(packageNameRule.evaluate(manifestDataPassing).status, 'pass');
  assert.equal(versionCodeRule.evaluate(manifestDataPassing).status, 'pass');
  assert.equal(versionNameRule.evaluate(manifestDataPassing).status, 'pass');
});

test('manifest-basics rules fail on missing fields', () => {
  assert.equal(packageNameRule.evaluate(manifestDataMissingFields).status, 'fail');
  assert.equal(versionCodeRule.evaluate(manifestDataMissingFields).status, 'fail');
  assert.equal(versionNameRule.evaluate(manifestDataMissingFields).status, 'fail');
});

test('runRules("android", ...) wires every rule and flags a blocking critical failure', () => {
  const findings = runRules('android', manifestDataFailingTargetSdk);
  assert.ok(findings.length >= 5, 'expected all registered android rules to run');

  const targetSdkFinding = findings.find((f) => f.id === 'android.manifest.target-sdk');
  assert.equal(targetSdkFinding.status, 'fail');
  assert.equal(targetSdkFinding.severity, 'critical');
});

test('runRules("android", ...) is all-pass on a clean manifest', () => {
  const findings = runRules('android', manifestDataPassing);
  const blocking = findings.filter((f) => f.status === 'fail' && f.severity === 'critical');
  assert.equal(blocking.length, 0);
});

test('isAutoGeneratedPermission recognizes the Android-generated RECEIVER_NOT_EXPORTED pattern and nothing else', () => {
  assert.equal(
    isAutoGeneratedPermission('tech.axiscore.align.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'),
    true
  );
  assert.equal(isAutoGeneratedPermission('android.permission.CAMERA'), false);
});

test('permissions-inventory rule expands into one finding per restricted permission, each with remediation', () => {
  const results = permissionsInventoryRule.evaluate(manifestDataSensitivePermissions);
  assert.ok(Array.isArray(results), 'expected evaluate() to return an array for this manifest');

  const overlay = results.find((r) => r.title && r.title.includes('SYSTEM_ALERT_WINDOW'));
  assert.ok(overlay, 'expected a dedicated finding for the restricted SYSTEM_ALERT_WINDOW permission');
  assert.equal(overlay.status, 'warn');
  assert.ok(overlay.remediation && overlay.remediation.length > 0);

  const dataSafety = results.find((r) => r.title === 'Data Safety form likely needs updating');
  assert.ok(dataSafety, 'expected a consolidated Data Safety reminder finding');
  assert.match(dataSafety.detail, /CAMERA/);

  const autoGenerated = results.some((r) => r.title && r.title.includes('DYNAMIC_RECEIVER_NOT_EXPORTED'));
  assert.equal(autoGenerated, false, 'the Android-auto-generated receiver permission must never be flagged');
});

test('runRules("android", ...) flattens the permissions rule and carries remediation through, never as a blocking failure', () => {
  const findings = runRules('android', manifestDataSensitivePermissions);
  const permissionFindings = findings.filter((f) => f.id.startsWith('android.manifest.permissions-inventory'));
  assert.ok(permissionFindings.length > 1, 'expected the permissions rule to expand into multiple findings');

  const passingFinding = findings.find((f) => f.id === 'android.manifest.package-name');
  assert.equal(passingFinding.remediation, null, 'a passing rule with no override should default remediation to null');

  const blocking = findings.filter((f) => f.status === 'fail' && f.severity === 'critical');
  assert.equal(blocking.length, 0, 'permission findings are advisory (warn), never blocking');
});
