import test from 'node:test';
import assert from 'node:assert/strict';
import { rule as targetSdkRule, MIN_REQUIRED_TARGET_SDK } from '../src/rules/android/target-sdk.js';
import {
  packageNameRule,
  versionCodeRule,
  versionNameRule,
} from '../src/rules/android/manifest-basics.js';
import { rule as permissionsInventoryRule } from '../src/rules/android/permissions-inventory.js';
import { isAutoGeneratedPermission } from '../src/rules/android/permission-catalog.js';
import {
  rule as appOptimizationRule,
  DEX_OPTIMIZATION_THRESHOLD_BYTES,
} from '../src/rules/android/app-optimization.js';
import { runRules } from '../src/rules/index.js';
import {
  manifestDataPassing,
  manifestDataFailingTargetSdk,
  manifestDataMissingFields,
  manifestDataSensitivePermissions,
  manifestDataUnoptimized,
  manifestDataOptimized,
  manifestDataSmallDexApp,
  manifestDataAmbiguousOwnClasses,
} from './fixtures/manifest-samples.js';

test('target-sdk rule fails below the required floor (catches the real Aug 2026 deadline)', () => {
  const result = targetSdkRule.evaluate(manifestDataFailingTargetSdk);
  assert.equal(result.status, 'fail');
  assert.match(result.detail, /35/);
  assert.match(result.detail, new RegExp(String(MIN_REQUIRED_TARGET_SDK)));
});

test('target-sdk rule passes at or above the required floor', () => {
  const result = targetSdkRule.evaluate(manifestDataPassing);
  assert.equal(result.status, 'pass');
});

test('target-sdk rule warns (not fails) when the value could not be read at all', () => {
  const result = targetSdkRule.evaluate(manifestDataMissingFields);
  assert.equal(result.status, 'warn');
});

test('manifest-basics rules pass on a well-formed manifest', () => {
  assert.equal(packageNameRule.evaluate(manifestDataPassing).status, 'pass');
  assert.equal(versionCodeRule.evaluate(manifestDataPassing).status, 'pass');
  assert.equal(versionNameRule.evaluate(manifestDataPassing).status, 'pass');
});

test('manifest-basics rules fail on missing fields', () => {
  assert.equal(packageNameRule.evaluate(manifestDataMissingFields).status, 'fail');
  assert.equal(versionCodeRule.evaluate(manifestDataMissingFields).status, 'fail');
  assert.equal(versionNameRule.evaluate(manifestDataMissingFields).status, 'fail');
});

test('runRules("android", ...) wires every rule and flags a blocking critical failure', () => {
  const findings = runRules('android', manifestDataFailingTargetSdk);
  assert.ok(findings.length >= 5, 'expected all registered android rules to run');

  const targetSdkFinding = findings.find((f) => f.id === 'android.manifest.target-sdk');
  assert.equal(targetSdkFinding.status, 'fail');
  assert.equal(targetSdkFinding.severity, 'critical');
});

test('runRules("android", ...) is all-pass on a clean manifest', () => {
  const findings = runRules('android', manifestDataPassing);
  const blocking = findings.filter((f) => f.status === 'fail' && f.severity === 'critical');
  assert.equal(blocking.length, 0);
});

test('isAutoGeneratedPermission recognizes the Android-generated RECEIVER_NOT_EXPORTED pattern and nothing else', () => {
  assert.equal(
    isAutoGeneratedPermission('tech.axiscore.align.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION'),
    true
  );
  assert.equal(isAutoGeneratedPermission('android.permission.CAMERA'), false);
});

test('permissions-inventory rule expands into one finding per restricted permission, each with remediation', () => {
  const results = permissionsInventoryRule.evaluate(manifestDataSensitivePermissions);
  assert.ok(Array.isArray(results), 'expected evaluate() to return an array for this manifest');

  const overlay = results.find((r) => r.title && r.title.includes('SYSTEM_ALERT_WINDOW'));
  assert.ok(overlay, 'expected a dedicated finding for the restricted SYSTEM_ALERT_WINDOW permission');
  assert.equal(overlay.status, 'warn');
  assert.ok(overlay.remediation && overlay.remediation.length > 0);

  const dataSafety = results.find((r) => r.title === 'Data Safety form likely needs updating');
  assert.ok(dataSafety, 'expected a consolidated Data Safety reminder finding');
  assert.match(dataSafety.detail, /CAMERA/);

  const autoGenerated = results.some((r) => r.title && r.title.includes('DYNAMIC_RECEIVER_NOT_EXPORTED'));
  assert.equal(autoGenerated, false, 'the Android-auto-generated receiver permission must never be flagged');
});

test('runRules("android", ...) flattens the permissions rule and carries remediation through, never as a blocking failure', () => {
  const findings = runRules('android', manifestDataSensitivePermissions);
  const permissionFindings = findings.filter((f) => f.id.startsWith('android.manifest.permissions-inventory'));
  assert.ok(permissionFindings.length > 1, 'expected the permissions rule to expand into multiple findings');

  const passingFinding = findings.find((f) => f.id === 'android.manifest.package-name');
  assert.equal(passingFinding.remediation, null, 'a passing rule with no override should default remediation to null');

  const blocking = findings.filter((f) => f.status === 'fail' && f.severity === 'critical');
  assert.equal(blocking.length, 0, 'permission findings are advisory (warn), never blocking');
});

test('app-optimization rule says nothing when the underlying signals are unavailable', () => {
  const results = appOptimizationRule.evaluate(manifestDataPassing); // no dexTotalBytes/hasBaselineProfile at all
  assert.deepEqual(results, []);
});

test('app-optimization rule warns on R8 minification when most own-package classes are still readable', () => {
  const results = appOptimizationRule.evaluate(manifestDataUnoptimized);

  const r8Finding = results.find((r) => r.id.endsWith('.r8-minification'));
  assert.equal(r8Finding.status, 'warn');
  assert.equal(r8Finding.severity, 'high');
  assert.match(r8Finding.detail, /18 of 20/);
  assert.match(r8Finding.remediation, /enableMinifyInReleaseBuilds/);
  assert.match(r8Finding.remediation, /minifyEnabled/);

  const baselineFinding = results.find((r) => r.id.endsWith('.baseline-profile'));
  assert.equal(baselineFinding.status, 'info');
  assert.ok(baselineFinding.remediation, 'missing baseline profile should carry remediation');
});

test('app-optimization rule passes when own-package classes look obfuscated, and confirms baseline profile presence', () => {
  const results = appOptimizationRule.evaluate(manifestDataOptimized);

  const r8Finding = results.find((r) => r.id.endsWith('.r8-minification'));
  assert.equal(r8Finding.status, 'pass');

  const baselineFinding = results.find((r) => r.id.endsWith('.baseline-profile'));
  assert.equal(baselineFinding.status, 'pass');
  // Note: raw evaluate() output has no remediation key at all on a pass — the
  // null-default only happens via runRules'/toFinding's `?? null`, which is
  // already covered by a separate test further up this file.
});

test('app-optimization rule stays quiet (info, not warn) under the 10MB dex threshold', () => {
  const results = appOptimizationRule.evaluate(manifestDataSmallDexApp);
  const r8Finding = results.find((r) => r.id.endsWith('.r8-minification'));
  assert.equal(r8Finding.status, 'info');
  assert.match(r8Finding.detail, /0\.5MB/);

  // manifestDataSmallDexApp also sets hasBaselineProfile: null (unavailable) — should be silent.
  assert.equal(results.some((r) => r.id.endsWith('.baseline-profile')), false);
});

test('app-optimization rule declines to guess when too few own-package classes are found', () => {
  const results = appOptimizationRule.evaluate(manifestDataAmbiguousOwnClasses);
  const r8Finding = results.find((r) => r.id.endsWith('.r8-minification'));
  assert.equal(r8Finding.status, 'info');
  assert.match(r8Finding.detail, /too few/i);
});

test('runRules("android", ...) never lets app-optimization findings block a scan', () => {
  const findings = runRules('android', manifestDataUnoptimized);
  const optimizationFindings = findings.filter((f) => f.id.startsWith('android.optimization.'));
  assert.ok(optimizationFindings.length >= 2, 'expected both sub-findings to run');

  const blocking = findings.filter((f) => f.status === 'fail' && f.severity === 'critical');
  assert.equal(blocking.length, 0, 'app-optimization findings are advisory (warn/info), never blocking');
});

test('DEX_OPTIMIZATION_THRESHOLD_BYTES matches the documented ~10MB figure', () => {
  assert.equal(DEX_OPTIMIZATION_THRESHOLD_BYTES, 10 * 1024 * 1024);
});
